version: '3.9'

services:
  wordle-helper:
    build:
      context: ./
      dockerfile: ./docker/DockerfileLocal
    volumes:
      - .:/code
    environment:
      - ENVIRONMENT=dev

  wordle-server:
    build:
      context: ./
      dockerfile: ./docker/DockerfileLocal
    command: uvicorn wordle.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev

  wordle-db:
    image: mongo:latest
    container_name: wordle-db
    hostname: wordle-db
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: mantium
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: wordle
    volumes:
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-data:/data/db
    ports:
      - '27017:27017'

  wordle-ui:
    build:
      context: ./
      dockerfile: ./docker/DockerfileLocalUI
    command: ["npm","start"]
    volumes:
      - ./ui:/ui
      - '/ui/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
